"""quotes.py"""

QUOTES: list[dict[str, str]] = [
        {"quote":"Amateurs hack systems; professionals hack people.","author":"Bruce Schneier","category":"cybersecurity"},
        {"quote":"Cybersecurity is a continuous cycle of protection, detection, response, and recovery.","author":"Chris Painter","category":"cybersecurity"},
        {"quote":"Cybersecurity is not just about protecting your devices. It's about protecting yourself.","author":"Anonymous","category":"cybersecurity"},
        {"quote":"Effective cybersecurity is not a product, but a process.","author":"Jim Langevin","category":"cybersecurity"},
        {"quote":"Hackers rarely have full knowledge of the technology stack of a target.","author":"John McAfee","category":"cybersecurity"},
        {"quote":"It's not enough to protect your data; you need to protect your customers' data too.","author":"Satya Nadella","category":"cybersecurity"},
        {"quote":"Security is not a one-time event. It's an ongoing process.","author":"John Malloy","category":"cybersecurity"},
        {"quote":"There's no silver bullet solution with cyber security, a layered defense is the only viable defense","author":"James Scott","category":"cybersecurity"},
        {"quote":"Mess with the best, die like the rest.","author":"Dade Murphy (Hackers)","category":"movie"},
        {"quote":"There is no right and wrong. There's only fun and boring.","author":"The Plague (Hackers)","category":"movie"},
        {"quote":"Never fear, I is here.","author":"The Plague (Hackers)","category":"movie"},
        {"quote":"This is your life and it's ending one minute at a time.","author":"The Narrator (Fight Club)","category":"movie"},
        {"quote":"Without pain, without sacrifice, we would have nothing.","author":"Tyler Durden (Fight Club)","category":"movie"},
        {"quote":"The things you own end up owning you.","author":"The Narrator (Fight Club)","category":"movie"},
        {"quote":"Garbage can provide important details for hackers: names, telephone numbers, a company's internal jargon.","author":"Kevin Mitnick","category":"cybersecurity"},
        {"quote":"The Internet is full of interesting things, you just have to know where to look.","author":"Kevin Mitnick","category":"cybersecurity"},
        {"quote":"Knowledge is free. We are Anonymous. We are Legion. We do not forgive. We do not forget. Expect us.","author":"Anonymous","category":"cybersecurity"},
        {"quote":"The only way to win is to cheat.","author":"Kevin Mitnick","category":"cybersecurity"},
        {"quote":"I'm not a hacker, I'm a security researcher.","author":"Many hackers","category":"cybersecurity"},
        {"quote":"The best way to learn is to teach.","author":"Linus Torvalds","category":"general"},
        {"quote":"The Internet is a dangerous place, but it's also a beautiful place.","author":"Kevin Mitnick","category":"cybersecurity"},
        {"quote":"The most dangerous people in the world are not the ones who break the rules, but the ones who follow them blindly.","author":"Anonymous","category":"cybersecurity"},
        {"quote":"The Internet is a powerful tool, but it can also be a dangerous weapon.","author":"Anonymous","category":"cybersecurity"},
        {"quote":"The future of warfare is cyberwarfare.","author":"Anonymous","category":"cybersecurity"},
        {"quote":"The only way to stay ahead of the hackers is to think like a hacker.","author":"Anonymous","category":"cybersecurity"},
        {"quote":"The only limit is your imagination.","author":"Kevin Mitnick","category":"cybersecurity"},
        {"quote":"The future belongs to those who can adapt.","author":"Anonymous","category":"cybersecurity"},
        {"quote":"The best way to learn is to do.","author":"Linus Torvalds","category":"general"},
        {"quote":"The only constant in life is change.","author":"Heraclitus","category":"general"},
        {"quote":"No man ever steps in the same river twice, for it's not the same river and he's not the same man","author":"Heraclitus","category":"general"},
        {"quote":"Slow is smooth, smooth is fast.","author":"Mark Divine (U.S. Navy SEAL)","category":"motivational"},
        {"quote":"The only easy day was yesterday.","author":"U.S. Navy SEAL","category":"motivational"},
        {"quote":"The journey of a thousand miles begins with a single step.","author":"Lao Tzu","category":"motivational"},
        {"quote":"Success is not final, failure is not fatal: It is the courage to continue that counts.","author":"Windston Churchill","category":"motivational"},
        {"quote":"The future belongs to those who believe in the beauty of their dreams.","author":"Rleanor Roosevelt","category":"motivational"},
        {"quote":"The only person you are destined to become is the person you decide to be.","author":"Ralph Waldo Emerson","category":"motivational"},
        {"quote":"The mind is everything. what you think you become.","author":"Budda","category":"motivational"},
        {"quote":"It does not matter how many times you fall down, but how many times you get back up.","author":"Vince Lombardi","category":"motivational"}
    ]